#define LIMPA printf("\x1B[2J")
#define POS_C(x, y) printf("\x1B[%d;%df", x, y)
#define APAG_L(x, y) printf("\x1B[K")
#define C_ESQ printf("\x1B[D")
#define C_DIR printf("\x1B[C")
#define C_SOBE printf("\x1B[A")
#define C_DESCE printf("\x1B[B")
#define C_ESQN(n) printf("\x1B[%dD",n)
#define C_DIRN(n) printf("\x1B[%dC",n)
#define C_SOBEN(n) printf("\x1B[%dA",n)
#define C_DESCEN(n) printf("\x1B[%dB",n)
#define NORMAL printf("\x1B[0m")
#define INTEN printf("\x1B[1m")
#define SUBL printf("\x1B[4m")
#define PISCA printf("\x1B[5m")
#define REV printf("\x1B[7m")
